/* The following code was generated by JFlex 1.4.3 on 02-22-15 07:49 PM */

package analizador;
import static analizador.Token.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 02-22-15 07:49 PM from the specification file
 * <tt>/Users/David/NetBeansProjects/analizadorLexico-Java/src/analizador/Lexer.flex</tt>
 */
class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\3\2\0\1\3\22\0\1\3\7\0\1\35\1\36"+
    "\1\11\1\10\1\0\1\12\1\0\1\7\12\2\1\0\1\34\1\6"+
    "\1\5\1\4\2\0\1\25\1\27\1\24\1\23\1\17\1\14\1\1"+
    "\1\16\1\13\2\1\1\21\1\1\1\20\1\30\1\32\1\1\1\26"+
    "\1\22\1\15\1\33\1\1\1\31\3\1\4\0\1\1\1\0\1\25"+
    "\1\27\1\24\1\23\1\17\1\14\1\1\1\16\1\13\2\1\1\21"+
    "\1\1\1\20\1\30\1\32\1\1\1\26\1\22\1\15\1\33\1\1"+
    "\1\31\3\1\uff85\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\12\2\1\14\1\1\1\15"+
    "\1\16\1\0\1\17\1\20\1\21\1\22\1\23\12\2"+
    "\1\0\1\24\1\25\11\2\1\0\1\26\5\2\1\27"+
    "\2\2\1\30\1\31\2\2\1\3\1\32\11\2\1\33"+
    "\1\2\1\34\3\2\1\35\1\36\1\2\1\37\4\2"+
    "\1\40\1\41\3\2\1\42\1\2\1\43\1\44";

  private static int [] zzUnpackAction() {
    int [] result = new int[102];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\37\0\76\0\135\0\37\0\174\0\233\0\272"+
    "\0\331\0\37\0\370\0\37\0\u0117\0\u0136\0\u0155\0\u0174"+
    "\0\u0193\0\u01b2\0\u01d1\0\u01f0\0\u020f\0\u022e\0\37\0\u024d"+
    "\0\37\0\37\0\u026c\0\37\0\37\0\37\0\37\0\76"+
    "\0\u028b\0\u02aa\0\u02c9\0\u02e8\0\u0307\0\u0326\0\u0345\0\u0364"+
    "\0\u0383\0\u03a2\0\u03c1\0\37\0\76\0\u03e0\0\u03ff\0\u041e"+
    "\0\u043d\0\u045c\0\u047b\0\u049a\0\u04b9\0\u04d8\0\u04f7\0\76"+
    "\0\u0516\0\u0535\0\u0554\0\u0573\0\u0592\0\u05b1\0\u05d0\0\u05ef"+
    "\0\76\0\76\0\u060e\0\u062d\0\37\0\76\0\u064c\0\u066b"+
    "\0\u068a\0\u06a9\0\u06c8\0\u06e7\0\u0706\0\u0725\0\u0744\0\76"+
    "\0\u0763\0\76\0\u0782\0\u07a1\0\u07c0\0\76\0\76\0\u07df"+
    "\0\76\0\u07fe\0\u081d\0\u083c\0\u085b\0\76\0\76\0\u087a"+
    "\0\u0899\0\u08b8\0\76\0\u08d7\0\76\0\76";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[102];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\3\1\20"+
    "\2\3\1\21\1\22\1\23\2\3\1\24\1\25\1\26"+
    "\2\3\1\27\1\30\1\2\40\0\2\3\10\0\21\3"+
    "\5\0\1\4\41\0\1\31\36\0\1\32\1\0\1\33"+
    "\34\0\1\34\40\0\1\35\1\0\1\36\34\0\1\37"+
    "\30\0\2\3\10\0\1\3\1\40\17\3\4\0\2\3"+
    "\10\0\15\3\1\41\3\3\4\0\2\3\10\0\3\3"+
    "\1\42\15\3\4\0\2\3\10\0\5\3\1\43\1\44"+
    "\12\3\4\0\2\3\10\0\4\3\1\45\14\3\4\0"+
    "\2\3\10\0\4\3\1\46\14\3\4\0\2\3\10\0"+
    "\3\3\1\47\15\3\4\0\2\3\10\0\15\3\1\50"+
    "\3\3\4\0\2\3\10\0\17\3\1\51\1\3\4\0"+
    "\2\3\10\0\3\3\1\52\15\3\15\0\1\53\31\0"+
    "\1\54\32\0\2\3\10\0\13\3\1\55\5\3\4\0"+
    "\2\3\10\0\4\3\1\56\14\3\4\0\2\3\10\0"+
    "\10\3\1\57\10\3\4\0\2\3\10\0\7\3\1\60"+
    "\11\3\4\0\2\3\10\0\6\3\1\61\12\3\4\0"+
    "\2\3\10\0\1\3\1\62\17\3\4\0\2\3\10\0"+
    "\12\3\1\63\6\3\4\0\2\3\10\0\15\3\1\64"+
    "\3\3\4\0\2\3\10\0\2\3\1\65\16\3\4\0"+
    "\2\3\10\0\1\66\20\3\5\0\1\67\35\0\2\3"+
    "\10\0\5\3\1\70\13\3\4\0\2\3\10\0\1\71"+
    "\1\72\5\3\1\73\1\74\4\3\1\75\3\3\4\0"+
    "\2\3\10\0\4\3\1\76\14\3\4\0\2\3\10\0"+
    "\4\3\1\77\14\3\4\0\2\3\10\0\12\3\1\100"+
    "\6\3\4\0\2\3\10\0\13\3\1\101\5\3\4\0"+
    "\2\3\10\0\6\3\1\102\12\3\4\0\2\3\10\0"+
    "\1\103\20\3\4\0\2\3\10\0\6\3\1\104\12\3"+
    "\5\0\1\67\33\0\1\105\1\0\2\3\10\0\1\3"+
    "\1\106\17\3\4\0\2\3\10\0\3\3\1\107\11\3"+
    "\1\110\3\3\4\0\2\3\10\0\4\3\1\111\14\3"+
    "\4\0\2\3\10\0\4\3\1\112\14\3\4\0\2\3"+
    "\10\0\17\3\1\113\1\3\4\0\2\3\10\0\1\114"+
    "\20\3\4\0\2\3\10\0\11\3\1\115\7\3\4\0"+
    "\2\3\10\0\20\3\1\116\4\0\2\3\10\0\15\3"+
    "\1\117\3\3\4\0\2\3\10\0\4\3\1\120\14\3"+
    "\4\0\2\3\10\0\1\121\20\3\4\0\2\3\10\0"+
    "\13\3\1\122\5\3\4\0\2\3\10\0\6\3\1\123"+
    "\12\3\4\0\2\3\10\0\1\3\1\124\17\3\4\0"+
    "\2\3\10\0\2\3\1\125\16\3\4\0\2\3\10\0"+
    "\1\3\1\126\17\3\4\0\2\3\10\0\2\3\1\127"+
    "\16\3\4\0\2\3\10\0\6\3\1\130\12\3\4\0"+
    "\2\3\10\0\5\3\1\131\13\3\4\0\2\3\10\0"+
    "\6\3\1\132\12\3\4\0\2\3\10\0\4\3\1\133"+
    "\14\3\4\0\2\3\10\0\12\3\1\134\6\3\4\0"+
    "\2\3\10\0\1\135\20\3\4\0\2\3\10\0\2\3"+
    "\1\136\16\3\4\0\2\3\10\0\4\3\1\137\14\3"+
    "\4\0\2\3\10\0\11\3\1\140\7\3\4\0\2\3"+
    "\10\0\20\3\1\141\4\0\2\3\10\0\15\3\1\142"+
    "\3\3\4\0\2\3\10\0\2\3\1\143\16\3\4\0"+
    "\2\3\10\0\6\3\1\144\12\3\4\0\2\3\10\0"+
    "\5\3\1\145\13\3\4\0\2\3\10\0\2\3\1\146"+
    "\16\3\3\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2294];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\2\1\1\11\4\1\1\11\1\1\1\11"+
    "\12\1\1\11\1\1\2\11\1\0\4\11\13\1\1\0"+
    "\1\11\12\1\1\0\15\1\1\11\41\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[102];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
public String lexeme;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 146) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 2: 
          { lexeme=yytext(); return ID;
          }
        case 37: break;
        case 19: 
          { return IF;
          }
        case 38: break;
        case 20: 
          { return NOTEQUAL;
          }
        case 39: break;
        case 3: 
          { lexeme=yytext(); return INT;
          }
        case 40: break;
        case 30: 
          { return SELECT;
          }
        case 41: break;
        case 10: 
          { return MULT;
          }
        case 42: break;
        case 17: 
          { return MCOMMENT;
          }
        case 43: break;
        case 36: 
          { return ENDDEFAULT;
          }
        case 44: break;
        case 5: 
          { return GREATERTHAN;
          }
        case 45: break;
        case 8: 
          { return DIV;
          }
        case 46: break;
        case 35: 
          { return ENDOPTION;
          }
        case 47: break;
        case 24: 
          { return CHAR;
          }
        case 48: break;
        case 11: 
          { return RESTA;
          }
        case 49: break;
        case 14: 
          { return EQUALS;
          }
        case 50: break;
        case 6: 
          { return ASSIGN;
          }
        case 51: break;
        case 9: 
          { return SUMA;
          }
        case 52: break;
        case 28: 
          { return ENDFOR;
          }
        case 53: break;
        case 15: 
          { return LESSOREQUALTHAN;
          }
        case 54: break;
        case 29: 
          { return ELSEIF;
          }
        case 55: break;
        case 22: 
          { return THEN;
          }
        case 56: break;
        case 23: 
          { return ELSE;
          }
        case 57: break;
        case 27: 
          { return WHILE;
          }
        case 58: break;
        case 16: 
          { return SCOMMENT;
          }
        case 59: break;
        case 34: 
          { return ENDSELECT;
          }
        case 60: break;
        case 26: 
          { return ENDIF;
          }
        case 61: break;
        case 18: 
          { return ENDMCOMMENT;
          }
        case 62: break;
        case 12: 
          { return LTERMINATOR;
          }
        case 63: break;
        case 7: 
          { return LESSTHAN;
          }
        case 64: break;
        case 31: 
          { return OPTION;
          }
        case 65: break;
        case 1: 
          { return ERROR;
          }
        case 66: break;
        case 21: 
          { return FOR;
          }
        case 67: break;
        case 32: 
          { return DEFAULT;
          }
        case 68: break;
        case 4: 
          { /*Ignore*/
          }
        case 69: break;
        case 33: 
          { return ENDWHILE;
          }
        case 70: break;
        case 25: 
          { return BOOL;
          }
        case 71: break;
        case 13: 
          { return GREATEROREQUALTHAN;
          }
        case 72: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
